##springboot+jdbc\u914D\u7F6E
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=THREEDAYS
    username: yta
    password: 123456
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
##servlet\u914D\u7F6E
server:
  servlet:
    context-path: /
##mybatis\u914D\u7F6E
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.threeDays.POJO
  mapper-locations: mapper/*.xml
